import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils import *

algorithms = [{"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": None, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0} 
,{"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.H, "target": 2, "control": None, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 0, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 0, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": None, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0} 
,{"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 1, "control": None, "params": None, "next": None, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0} 
,{"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.H, "target": 2, "control": None, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.H, "target": 2, "control": None, "params": None, "next": {"instruction": Instruction.H, "target": 2, "control": None, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": None, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0} 
,{"instruction": Instruction.H, "target": 2, "control": None, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 0, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 0, "params": None, "next": {"instruction": Instruction.CNOT, "target": 1, "control": 2, "params": None, "next": None, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0}, "case0": None, "case1": None, "count_meas": 0, "depth": 0} 
]