sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b5.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b20.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b7.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b27.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b65.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b28.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b16.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b15.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b53.json
sbatch experiments_script.sh /nfs/scistore16/tomgrp/smuroyal/im_time_evolution/configs/cxh_b127.json
